=== RafaelSilva29/PRI/TPC2/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT project-record (meta,work-team,abstract,deliverables) >

<!ELEMENT meta (key-name,title,sub-title?,begin-date?,end-date?,supervisor) >
<!ELEMENT key-name (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT sub-title (#PCDATA) >
<!ELEMENT begin-date (#PCDATA) >
<!ELEMENT end-date (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >

<!ELEMENT work-team (member)+ >
<!ELEMENT member (#PCDATA) >

<!ELEMENT abstract (paragraph)+ >
<!ELEMENT paragraph (#PCDATA) >

<!ELEMENT deliverables (deliverable)* >
<!ELEMENT deliverable (#PCDATA) >

<!ATTLIST paragraph
    italic CDATA #IMPLIED
    bold CDATA  #IMPLIED >
    
<!ATTLIST supervisor
    link CDATA #REQUIRED >
    
<!ATTLIST member
    email CDATA #REQUIRED >
   
<!ATTLIST deliverable
    link CDATA #IMPLIED >

=== RafaelSilva29/PRI/TPCs/TPC2/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "pr.dtd">
<project-record>
    <meta>
        <key-name>PRI2019-A74264-T2</key-name>
        <title>Create a project record</title>
        <begin-date>30 de Setembro</begin-date>
        <end-date>1 de Outubro</end-date>
        <supervisor link="http://www4.di.uminho.pt/~jcr/"></supervisor>
    </meta>
    <work-team>
        <member email="a74264@alunos.uminho.pt">Rafael Machado da Silva</member>
    </work-team>
    <abstract>
        <paragraph>A XML file to work with the project record that was develop.</paragraph>
    </abstract>
    <deliverables>
        <deliverable link="http://www4.di.uminho.pt/~jcr/XML/didac/xmldocs/PR.htm">Example of a Project Record.</deliverable>
    </deliverables>
</project-record>
